# Generated by Django 3.2.12 on 2022-08-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chordproapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_by',
        ),
    ]
