# Generated by Django 3.2.12 on 2022-08-09 13:38

from django.db import migrations

# Generated by Django 3.2.12 on 2022-08-09 09:14

from django.db import migrations


def create_dummy_songs(apps, schema_editor):
    Song = apps.get_model('chordproapi', 'Song', 'User')

    Song(title='Coucou', author='c moi', base_key='A', tempo='80', content='test').save()
    Song(title='Salut', author='c pas moi', base_key='G', tempo='120', content='asdf').save()
    Song(title='Yo', author='askip', base_key='Em', tempo='90', content='lkjh').save()

class Migration(migrations.Migration):

    dependencies = [
        ('chordproapi', '0003_auto_20220809_1336'),
    ]

    operations = [
        migrations.RunPython(create_dummy_songs),
    ]
